$primary = rgb(229,196,73)
$surface =  rgb(21,19,14)
$secondary = rgb(211,198,161)
$error = rgb(255,180,171)
$tertiary = rgb(171,208,176)
$surface_lowest = rgb(16,14,9)
$surface_highest = rgb(55,52,46)

general {
    col.active_border = $primary $secondary 80deg
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
