animations {
    enabled = true
    bezier = elastic, 0.05, 0.9, 0.1, 1.05
    bezier = retro, 0.6, -0.28, 0.735, 0.045
    bezier = smooth, 0.1, 1, 0.1, 1
    animation = windowsIn, 1, 6, elastic, popin 80%
    animation = windowsOut, 1, 5, retro, popin 80%
    animation = windowsMove, 1, 5, smooth, slide
    animation = fade, 1, 5, smooth
    animation = workspaces, 1, 6, elastic, slide
    animation = specialWorkspace, 1, 6, elastic, slidevert
}