animations {
    enabled = yes
    bezier = glass, 0.16, 1, 0.3, 1
    bezier = fade, 0.33, 1, 0.68, 1
    animation = windowsIn, 1, 6, glass, slide
    animation = windowsOut, 1, 6, glass, popin 90%
    animation = windowsMove, 1, 6, glass, slide
    animation = fade, 1, 7, fade
    animation = layers, 1, 6, glass, fade
    animation = workspaces, 1, 6, glass, slidefade 10%
}