animations {
    enabled = true
    bezier = pulse, 0.1, 0.9, 0.1, 1.05
    bezier = quick, 0.2, 1, 0.2, 1
    animation = windowsIn, 1, 6, pulse, slide
    animation = windowsOut, 1, 4, quick, slide
    animation = windowsMove, 1, 5, pulse, slide
    animation = fade, 1, 5, pulse
    animation = layers, 1, 5, pulse, popin
    animation = workspaces, 1, 6, pulse, slidefade 40%
}