animations {
    enabled = true
    bezier = anticipate, 0.1, -0.1, 0.1, 1.0
    bezier = inertia, 0.05, 0.9, 0.1, 1.05
    bezier = friction, 0.05, 0.9, 0.1, 1.0
    animation = windowsIn, 1, 5, inertia, slide
    animation = windowsOut, 1, 6, anticipate, slide
    animation = windowsMove, 1, 5, friction, slide
    animation = fade, 1, 5, friction
    animation = layers, 1, 5, friction, fade
    animation = workspaces, 1, 6, inertia, slidefade 20%
}
