animations {
    enabled = yes
    bezier = rubber, 0.05, 0.9, 0.1, 1.15
    bezier = snap, 0.1, 1, 0, 1
    animation = windowsIn, 1, 5, rubber, slidevert
    animation = windowsOut, 1, 4, snap, slidevert
    animation = windowsMove, 1, 5, rubber, slide
    animation = fade, 1, 4, default
    animation = layers, 1, 4, rubber, slidevert
    animation = workspaces, 1, 6, rubber, slidevert
}