animations {
    enabled = true
    bezier = holo, 0.23, 1, 0.32, 1
    bezier = data, 0.16, 1, 0.3, 1
    animation = windowsIn, 1, 5, holo, slide
    animation = windowsOut, 1, 4, holo, popin 100%
    animation = windowsMove, 1, 5, holo, slide
    animation = fade, 1, 5, data
    animation = layers, 1, 5, holo, fade
    animation = workspaces, 1, 6, holo, slidevert
    animation = specialWorkspace, 1, 6, holo, slidevert
}