animations {
    enabled = true
    bezier = linear, 0.0, 0.0, 1.0, 1.0
    animation = windowsIn, 1, 5, linear, slide
    animation = windowsOut, 1, 5, linear, slide
    animation = windowsMove, 1, 5, linear, slide
    animation = fade, 1, 4, linear
    animation = layers, 1, 4, linear, fade
    animation = workspaces, 1, 5, linear, slide
}