animations {
    enabled = yes
    bezier = sprout, 0.25, 0.8, 0.25, 1.0
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    animation = windowsIn, 1, 6, sprout, popin 85%
    animation = windowsOut, 1, 5, sprout, popin 95%
    animation = windowsMove, 1, 5, wind, slide
    animation = fade, 1, 7, sprout
    animation = layers, 1, 5, sprout, popin
    animation = workspaces, 1, 6, sprout, slidevert
}