animations {
    enabled = true
    bezier = spring, 0.05, 0.9, 0.1, 1.1
    bezier = crouch, 0.1, -0.1, 0.1, 1.0
    animation = windowsIn, 1, 5, spring, popin 80%
    animation = windowsOut, 1, 5, crouch, popin 80%
    animation = windowsMove, 1, 5, spring, slide
    animation = fade, 1, 3, default
    animation = fadeLayersIn, 1, 3, default
    animation = layers, 1, 4, spring, popin
    animation = workspaces, 1, 5, spring, slidevert
}