animations {
    enabled = true
    bezier = jump, 0.5, -0.3, 0.68, 1.4
    bezier = squash, 0.5, -0.5, 0.1, 1.0
    bezier = rubber, 0.05, 0.9, 0.1, 1.05
    animation = windowsIn, 1, 5, jump, popin 80%
    animation = windowsOut, 1, 4, squash, popin 80%
    animation = windowsMove, 1, 4, rubber, slide
    animation = fade, 1, 3, default
    animation = workspaces, 1, 5, jump, slide
}