animations {
    enabled = true
    bezier = soft, 0.25, 1, 0.5, 1
    bezier = focus, 0.16, 1, 0.3, 1
    animation = windowsIn, 1, 5, soft, popin 95%
    animation = windowsOut, 1, 4, focus, popin 98%
    animation = windowsMove, 1, 5, soft, slide
    animation = fade, 1, 4, soft
    animation = layers, 1, 4, soft, popin
    animation = workspaces, 1, 5, soft, slidefade 5%
}