color0 #15130e
color1 #ffb4ab
color2 #e5c449
color3 #d3c6a1
color4 #abd0b0
color5 #e5c449
color6 #d3c6a1
color7 #e8e2d9
color8 #979080
color9 #ffb4ab
color10 #e5c449
color11 #d3c6a1
color12 #abd0b0
color13 #e5c449
color14 #d3c6a1
color15 #e8e2d9

cursor                #e8e2d9
cursor_text_color     #15130e
background            #15130e
foreground            #e8e2d9
selection_foreground  #cec6b4
selection_background  #4b4639
active_border_color   #e5c449
inactive_border_color #4b4639
url_color             #e5c449

active_tab_foreground   #3b2f00
active_tab_background   #e5c449
inactive_tab_foreground #cec6b4
inactive_tab_background #4b4639
cursor_trail_color      #cec6b4
