#!/usr/bin/env bash
# shellcheck shell=bash
# =============================================================================
# Stow Manager Module: Recursive Package Content Scanner
# =============================================================================

scan_package_dependencies() {
    local pkg="$1"
    local pkg_dir="$DOTFILES_DIR/$pkg"

    if [[ ! -d "$pkg_dir" ]]; then
        error "Package directory '${pkg}' does not exist!"
        return 1
    fi

    info "Recursively scanning package content in '${pkg}' for dependencies..."

    local detected_shebangs=()
    local detected_cmds=()

    # 1. Scan Shebangs (e.g. #!/bin/zsh, #!/usr/bin/env bash)
    while IFS= read -r file; do
        if [[ -f "$file" ]]; then
            local first_line
            first_line="$(head -n 1 "$file" 2>/dev/null || true)"
            if [[ "$first_line" =~ ^#! ]]; then
                local bin
                bin="$(echo "$first_line" | awk '{print $NF}' | xargs basename 2>/dev/null || true)"
                if [[ -n "$bin" && "$bin" != "env" && "$bin" != "sh" ]]; then
                    detected_shebangs+=("$bin")
                fi
            fi
        fi
    done < <(find "$pkg_dir" -type f 2>/dev/null)

    # 2. Dynamically gather candidate tool list from registry and all package manifests
    local candidate_tools=()
    read -r -a candidate_tools <<< "$(get_all_registry_tools)"

    read -r -a packages <<< "$(get_all_packages)"
    for p in "${packages[@]}"; do
        local req_t
        local opt_t
        req_t="$(read_manifest_key "$p" "REQUIRED")"
        opt_t="$(read_manifest_key "$p" "OPTIONAL")"
        for t in $req_t $opt_t; do
            candidate_tools+=("$t")
        done
    done

    read -r -a unique_candidates <<< "$(echo "${candidate_tools[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')"

    for tool in "${unique_candidates[@]}"; do
        if grep -rq -E "(command -v ${tool}|exec ${tool}|alias .*=${tool}|${tool} init|${tool} -c)" "$pkg_dir" 2>/dev/null; then
            detected_cmds+=("$tool")
        fi
    done

    # Combine & deduplicate
    read -r -a unique_req <<< "$(echo "${detected_shebangs[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')"
    read -r -a unique_opt <<< "$(echo "${detected_cmds[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')"

    info "Scan Results for package '${pkg}':"
    echo -e "  ${BOLD}Detected Shebangs (Required):${NC} ${unique_req[*]:-none}"
    echo -e "  ${BOLD}Detected Invocations (Optional):${NC} ${unique_opt[*]:-none}\n"

    local manifest="$pkg_dir/.stowdeps"
    if [[ ! -f "$manifest" ]]; then
        info "Auto-generating '.stowdeps' manifest for '${pkg}'..."
        cat <<EOF > "$manifest"
# Package Dependency Manifest for '${pkg}' (auto-generated by stow.sh scan)
REQUIRED="${unique_req[*]}"
OPTIONAL="${unique_opt[*]}"
CONFLICTS=""
EOF
        success "Generated '${manifest}'"
    fi
}
