$primary = {{colors.primary.default.rgb | replace: " ", ""}}
$surface =  {{colors.surface.default.rgb | replace: " ", ""}}
$secondary = {{colors.secondary.default.rgb | replace: " ", ""}}
$error = {{colors.error.default.rgb | replace: " ", ""}}
$tertiary = {{colors.tertiary.default.rgb | replace: " ", ""}}
$surface_lowest = {{colors.surface_container_lowest.default.rgb | replace: " ", ""}}
$surface_highest = {{colors.surface_container_highest.default.rgb | replace: " ", ""}}

general {
    col.active_border = $primary $secondary 80deg
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
