[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
[templates.hyprland]
input_path = "~/.config/noctalia/templates/hyprlandborders.conf"
output_path = "~/.config/hypr/noctalia/noctalia-colors.conf"

[templates.hyprlua]
input_path = "~/.config/hypr/modules/hyprlandborders.lua"
output_path = "~/.config/hypr/noctalia/noctalia-colors.lua"

[templates.neovim]
input_path = "~/.config/noctalia/templates/neovim.lua"
output_path = "~/Projects/colors.nvim/lua/dcolorscheme/neovim.lua"
