[theme.templates.user.hyprlua]
input_path = "./templates/hyprland.lua"
output_path = "~/.config/hypr/noctalia/noctalia-colors.lua"
post_hook = "hyprctl reload"

[theme.templates.user.neovim]
input_path = "./templates/neovim.lua"
output_path = "~/Projects/colors.nvim/lua/dcolorscheme/neovim.lua"
