$configs = ~/.config/hypr

source = $configs/keybinds.conf
source = $configs/decorations.conf
source = $configs/windowrules.conf
source = $configs/animations.conf
source = $configs/noctalia/noctalia-colors.conf

monitor= , highres, auto, 1.20
#monitor= DP-2, preferred, -1920x0, 1
xwayland{
  force_zero_scaling = true
}

exec-once = uwsm app -- /usr/lib/pam_kwallet_init
exec-once = uwsm app -- /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = uwsm app -- qs -c noctalia-shell
exec-once = echo "Xft.dpi: 128" | xrdb -merge
