windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
  # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = fix_gimp
    match:class = ^(gimp)$
    border_color = rgba(b3ff1a)
    tile = off
}

# WORKSPACE DELEGATION

windowrule {
    name = libreoffice
    match:class = (.*libreoffice-.*)
    border_color = rgba(b3ff1a)
    workspace = 3
    opaque = on
}

windowrule {
    name = game
    match:class = ^(steam_proton|steam_app.*)$
    fullscreen = on
    opaque = on
    workspace = 9 silent
}

windowrule {
  name = browsers
  match:class = ^(brave.*)$
  workspace = 2
}

windowrule {
  name = terminals
  match:class = ^(kitty.*)$
  workspace = 1
}

windowrule {
    name = media_viewers
    match:class = ^(mpv|feh)$
    tile = off
    center = on
    opaque = on
  workspace = 4
}

###

windowrule {
    name = float_dialogs
    match:class = ^(org.freedesktop.impl.portal.*)$
    tile = off
    persistent_size = on
}

windowrule {
    name = steam_floating
    match:class = ^(steam)$
    match:title = ^(Friends List|Steam - News|.*Settings.*|.* - Chat|Players|Game Servers|Recordings &.*)$
    tile = off
    center = on
}

windowrule = match:class ^(com.obsproject.Studio)$, match:title ^(Settings|Projector.*)$, tile off, center on
windowrule = match:class ^(code|visual-studio-code-bin)$, match:title ^(Open Folder|Save As|Extension.*)$, tile off
windowrule = tile on, maximize on, match:class ^(gimp)$, match:title (.*GNU Image Manipulation Program.*)
windowrule = opaque on, match:class ^(gimp)$, match:title (.*GNU Image Manipulation Program.*)
windowrule = match:float true, center on, persistent_size off
windowrule = tile off, center on, size 500 750, match:class ^(brave.*)$, match:title ^(DevTools.*|Untitled.*)$
windowrule = float on, decorate off, match:modal true
